kind = "mobile"
previewPath = "/"
title = "Meus Filmes"
version = "1.0.0"
id = "artifacts/filmes"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19479

[services.development]
run = "pnpm --filter @workspace/filmes run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/filmes", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/filmes", "run", "serve" ]

[services.env]
PORT = "19479"
BASE_PATH = "/"
